name = "Mistry Siddh"
license = "MIT"
licenselink = "https://github.com/mrfoxie/mistrysiddh-theme/blob/master/LICENSE"
description = "Myself Mistry Siddh, I’m a blogger who loves to write conspiracy theories, NEWS, tips&tricks, etc."
homepage = "https://mistrysiddh.tk"
tags = ["accessible", "multilingual", "responsive", "blog", "search", "simple", "light", "dark", "mobile", "gallery", "technical", "fast", "presentation"]
features = ["accessible", "multilingual", "responsive", "grid", "sass", "search", "subtheme", "gallery", "technical", "fast", "presentation"]
min_version = "0.65.0"

[author]
  name = "Mistry Siddh"
  homepage = "https://github.com/mrfoxie/mistrysiddh"
